const ADD_USER = "ADD_USER";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";
const SET_SELECTED_USER = "SET_SELECTED_USER";

export {
    ADD_USER,
    UPDATE_USER,
    DELETE_USER,
    SET_SELECTED_USER
}